# -*- coding: utf-8 -*-
"""Python • Estrutura de Comparação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vWA0Yo_I82F-VGd4PqbAIgjDGhhB8QwF
"""

1 - Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo.

n1 = float(input('Insira um número: '))
print(' ')

if n1 < 0:
  print('Esse número é Negativo!')
else:
  print('Esse número é Positivo!')

"""2 - Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.

"""

s = input('Identifique o seu sexo (F - M): ')
s = s.upper ()
print(' ')


if s == 'F':
  print('Sexo Feminino!')
elif s == 'M':
  print('Sexo Masculino!')
else:
  print('Gênero Inválido')

"""3 - Faça um Programa que verifique se uma letra digitada é vogal ou consoante."""

l = str(input('Digite uma letra: '))
l = l.lower() #caso digite em maísculo/minusculo ambas as formas vão ser consideradas!
print(' ')

if l == ('a' or 'e' or 'i' or 'o' or 'U'):
  print('Essa letra é uma vogal!')
else:
  print('Essa letra é uma consoante!')

"""4 - Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno apresentar:

• A mensagem "Aprovado", se a média alcançada for maior ou igual a sete;

• A mensagem "Reprovado", se a média for menor do que sete;

• A mensagem "Aprovado com Distinção", se a média for igual a dez.
"""

print('Bem-vindo ao calculador de médias!')
print(' ')
print(' ')

n1 = float(input('Insira a primeira nota: '))
n2 = float(input('Insira a segunda nota: '))

soma = n1 + n2

media = soma/2

print(' ')
print(' ')
print('Sua média é: ', media)

if media == 10:
  print('Parabéns, você foi APROVADO COM DISTINÇÃO!')
elif media >= 7:
  print('Parabéns, Você foi APROVADO!')
else:
  print('Você foi REPROVADO!')

"""5 - Faça um Programa que leia três números e mostre o maior deles."""

print('Vamos verificar qual o maior número...')
print(' ')
print(' ')

n1 = float(input('Digite um número: '))
n2 = float(input('Digite outro número: '))
n3 = float(input('Digite outro número: '))

maior = max(n1, n2, n3)

print(' ')
print(' ')

print('O maior número é: ', maior)

"""6 - Faça um Programa que leia três números e mostre o maior e o menor deles."""

print('Vamos verificar qual o maior e o menor número...')
print(' ')
print(' ')

n1 = float(input('Digite um número: '))
n2 = float(input('Digite outro número: '))
n3 = float(input('Digite outro número: '))

maior = max(n1, n2, n3)
menor = min(n1, n2, n3)

print(' ')
print(' ')

print('O maior número é: ', maior)
print('O menor número é: ', menor)

"""7 - Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

print('Vamos comparar os valores dos produtos...')
print(' ')
print(' ')

p1 = float(input('Insira o preço do primeiro produto: '))
p2 = float(input('Insira o preço do segundo produto: '))
p3 = float(input('Insira o preço do terceiro produto: '))

print(' ')
print(' ')
print('Verificando o menor preço...')

menor = min(p1, p2, p3)
print(' ')
print(' ')


print('Recomendamos que você compre o de R$ ', menor)

"""8 - Faça um Programa que leia três números e mostre-os em ordem decrescente.

"""



"""9 - As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:

• Salários até R$ 280,00 (incluindo) : aumento de 20%

• Salários entre R$ 280,00 e R$ 700,00 : aumento de 15%

• Salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%

• Salários de R$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:

• O salário antes do reajuste;

• O percentual de aumento aplicado;

• O valor do aumento;

• O novo salário, após o aumento.
"""



"""10 - Faça um Programa que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.
Dicas: Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro.

• Triângulo Equilátero: três lados iguais;

• Triângulo Isósceles: quaisquer dois lados iguais;

• Triângulo Escaleno: três lados diferentes;


"""

print('Vamos verificar as medidas de um trinâgulo?')
print(' ')

l1 = float(input('Insira o primeiro lado do triângulo: '))
l2 = float(input('Insira o segundo lado do trinângulo: '))
l3 = float(input('Insrira o terceiro lado do triângulo: '))

print(' ')
print(' ')

print('Verificando se é um trinângulo...')
print(' ')

if (l1 < l2 + l3) and (l2 < l1 + l3) and (l3 < l1 + l2):
  print('Isso é um triângulo!')
else:
  print('Isso não é um triângulo!')

print(' ')
print(' ')

if (l1 == l2 == l3):
  print('É um triângulo Equilátero!')
elif (l1 != l2 != l3):
  print('É um triângulo Escaleno!')
else:
  print('É um triângulo Isósceles!')