# -*- coding: utf-8 -*-
"""Python • Estrutura de Repetição

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUOjTwLNf2klJGIRiYkyCK0ZwHJPF0VQ

1 - Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

nota = float(input('Insira a nota do aluno: '))
print(' ')
print(' ')

while nota<0 or nota>10:
  print('Nota inválida! por favor insira uma nota entre 0.0 e 10.0 ')
  nota = float(input('Insria a nota do aluno: '))
print(' ')
print(' ')
print('Nota registrada com sucesso!')

"""2 - Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

user = input('Insira o nome do usuário: ')
password = input('Insira a senha: ')

while user == password:
  print('Não aceitamos o usuário e a senha com a mesma sequência. Por favor insira um login válido!')
  print(' ')
  print(' ')
  user = input('Insira o nome do usuário: ')
  password = input('Insira a senha: ')


print(' ')
print(' ')
print('Acesso realizado com sucesso!')

"""3 - Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.

"""

print('Números abaixo um do outro:')
print()
print()

for i in range(1,21):
  print(i)

print('Números um ao lado do outro:')
print()
print()

for i in range(1,21):
  print(i, end= ' | ')

"""4 - Faça um programa que leia 5 números e informe o maior número"""

maior = 0

for i in range(0, 5):
  num = float(input('Digite um número: '))
  if num > maior:
    maior = num

print(' ')
print(' ')
print(' ')
print('O maior número é: ', maior)

"""5 - Faça um programa que leia 5 números e informe a soma e a média dos números.

"""

print('Vamos verifcar a soma e a média de alguns números? Simbora!!')
print()
print()

soma = 0

for i in range (1, 6):
  num = float(input('Digite um número: '))
  soma += num # ou seja: soma = soma + num
  media = soma/i

print()
print()

print('A soma dos números é: ', soma)
print()
print('A média corresponde a: ', media)

"""6 - Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50."""

for i in range(1,51):
  if i%2 != 0:
    print (i)

"""7 - Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.
Altere o programa anterior para mostrar no final a soma dos números.

"""

n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))

print()
print()

soma = 0

for i in range((n1+1), n2):
  print (i, end= ' | ')
  soma += i

print()
print()
print('A soma desse intervalo é: ', soma)

"""8 - Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:


---


Tabuada de 5:

5 X 1 = 5

5 X 2 = 10

[...]

5 X 10 = 50


---


"""

print('Bem-vindo(a) a tabuada! ')
print()
print()
tab = int(input('Digite um número entre 1 a 10 para encontra-lá:'))

print()
print()
if tab > 10 or tab < 1 :
  print('Número inválido!')
else:
  print(f'| Tabuada do {tab} |')

for i in range (1,11):
  print(f'{tab} x {i} = {tab*i}')

"""9 - Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

base = int(input('Digite um número para a base: '))
expo = int(input('Digite um número para o expoente: '))
result = 1

print()
print()
print()

for i in range(expo):
    result *= base

print(f'Resultamos em: {base} ^ {expo} = {result}')

"""10 - Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

par = 0
impar = 0

for i in range(10):
  num = int(input('Digite um número inteiro: '))
  if num % 2 == 0:
    par += 1
  else:
    impar += 1

print()
print()

print('Quantidade de números pares:', par)
print('Quantidade de números ímpares:', impar)

"""11 - A série de Fibonacci é formada pela seqüência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o n−ésimo termo.

"""



"""12 - A série de Fibonacci é formada pela seqüência 0,1,1,2,3,5,8,13,21,34,55,... Faça um programa que gere a série até que o valor seja maior que 500.

"""



"""13 - Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120"""

fat = int(input('Insira um número a ser fatorado!: '))
num = fat
print()
print()

for i in range(fat- 1, 1, -1):
  print(f' {fat} x {i} = {fat * i} ')
  fat *= i

print()
print()
print()

print(f'O fatorial de {num} é: ', fat)