# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCk6gW1xpXAzyhrOURooc9FRRI1GgkqP

1 - Faça um Programa que mostre a mensagem "Alo mundo" na tela.
"""

print ('Alo Mundo')

"""2 - Faça um Programa que peça um número e então mostre a mensagem."""

input ('Insira um número, por gentileza!: ')

"""3 - Faça um Programa que peça dois números e imprima a soma.

"""

n1 = float(input('Insira um número!: '))
n2 = float(input('Insira outro número!: '))

print ('Realizando a soma...')

n3 = n1 + n2

print ('A soma dos números: ', n3)

"""4 - Faça um Programa que peça as 4 notas bimestrais e mostre a média."""

print ('Vamos dá olhadinha na sua média?!')

n1 = float(input('Insira a primeira nota: '))
n2 = float(input('Insira a segunda nota: '))
n3 = float(input('Insira a terceira nota: '))
n4 = float(input('Insira a quarta nota: '))

somaTudo = n1 + n2 + n3 + n4
print ('Realizando a média...')

media = somaTudo/4

print ("A sua média é: ", media)

"""5 - Faça um Programa que converta metros para centímetros."""

m = float(input('Insira uma medida em metros para converter!: '))

centi = m * 100

print("A medida em centimetros equivale a: ", centi)

"""6 - Faça um Programa que peça o raio de um círculo, calcule e mostre sua área."""

print('Vamos descobrir a área do círculo? Ela se dá pela fórmula: A = π r²')

p = float(input('Insira o número que vamos considerar PI! (Exemplo: 3.14 ou 3...): '))
r = float(input('Insira o valor do raio: '))

A = p * (r**2)

print('A área do círculo é: ', A)

"""7 - Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

print('Vamos calcular a área do quadrado! Ela se dá pela fórmula: A = l²')

print(' ')

l = float(input('Insira a medida do lado do quadrado: '))

A = l ** 2
d = A * 2

print('A área do quadrado é: ', A)

print(' ')

print('O dobro dessa área é: ', d)

"""8 - Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês."""

print('Vamos dá uma olhadinha no valor do seu salário?')
print(' ')

"""9 - Faça um Programa que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius. C = 5 * ((F-32) / 9)."""



"""10 - Faça um Programa que peça a temperatura em graus Celsius, transforme e mostre em graus Fahrenheit."""

